all: compile run clean

run:
	./ex1A2P.o
	./ex1B2P.o
	./ex1C2P.o
	./ex1D2P.o

compile:
	gcc ex1A.c -o ex1A2P.o
	gcc ex1B.c -o ex1B2P.o
	gcc ex1C.c -o ex1C2P.o
	gcc ex1D.c -o ex1D2P.o

clean:
	rm -f *.o


ex2:
	gcc ex2.c -o ex2P
	./ex2P
	@echo -n "\n\nbella bro make file si chiude\n\n"
ex3:
	gcc ex3.c -o ex3P
	./ex3P
