-- Trigger for managing the update of the DNAME field in DIP
CREATE OR REPLACE TRIGGER UP_SAL
AFTER UPDATE OF DNAME ON DIP
FOR EACH ROW
WHEN ( OLD . DNAME ='ACCOUNTING ' AND NEW . DNAME ='SALES ')
BEGIN
UPDATE IMP
SET SAL = SAL +100
WHERE DEPTNO =: OLD . DEPTNO ;
END ;
/
