-- Triggers for managing the insertion of a record in IMP
CREATE OR REPLACE TRIGGER INS_IMP
AFTER INSERT ON IMP
FOR EACH ROW
DECLARE
N NUMBER ;
M NUMBER ;
BEGIN

SELECT COUNT (*) INTO N
FROM SUMMARY
WHERE JOB =: NEW . JOB ;
IF ( N =0) THEN
	INSERT INTO SUMMARY ( JOB , NUM )
	VALUES (: NEW . JOB , 1);
ELSE
	SELECT NUM INTO M
	FROM SUMMARY
	WHERE JOB =: NEW . JOB ;
	UPDATE SUMMARY
	SET NUM = M +1
	WHERE JOB =: NEW . JOB ;
END IF ;
END ;
/
