-- Trigger for managing the update of the JOB field in IMP.
CREATE OR REPLACE TRIGGER UPD_IMP
AFTER UPDATE OF JOB ON IMP
FOR EACH ROW
DECLARE
N NUMBER ;
M NUMBER ;
BEGIN
SELECT COUNT (*) INTO N
FROM SUMMARY
WHERE JOB =: NEW . JOB ;
IF ( N =0) THEN
	INSERT INTO SUMMARY ( JOB , NUM )
	VALUES (: NEW . JOB , 1);	
ELSE
	UPDATE SUMMARY
	SET NUM = NUM +1
	WHERE JOB =: NEW . JOB ;
	END IF ;
	SELECT NUM INTO M
	FROM SUMMARY
	WHERE JOB =: OLD . JOB ;
IF ( M =1) THEN
	DELETE FROM SUMMARY
	WHERE JOB =: OLD . JOB ;
ELSE

UPDATE SUMMARY
SET NUM = NUM -1
WHERE JOB =: OLD . JOB ;
END IF ;
END ;
/