---
title: "Esempio Shiny - Redditi 2020"
output: html_document
runtime: shiny
---

### Dataset

SI utilizza un dataset proveniente dagli [Open-Data del Ministero delle Finanze](https://www1.finanze.gov.it/finanze/analisi_stat/public/index.php?opendata=yes)

In particolare i dati relativi ai redditi ei dati IRPEF relativi alle dichiarazioni dei redditi dell'anno fiscale 2020.
Scaricabile da: <https://www1.finanze.gov.it/finanze/analisi_stat/public/v_4_0_0/contenuti/Redditi_e_principali_variabili_IRPEF_su_base_comunale_CSV_2020.zip?d=1615465800>

```{r setup, echo=FALSE, include=FALSE}
library(tidyverse)
library(scales)
library(sf)
library(shiny)

redditi <- read_csv2("Redditi_e_principali_variabili_IRPEF_su_base_comunale_CSV_2020.zip") %>% 
           rename(Comune=4, Provincia=5, contribuenti=8, imponibile_n=23, imponibile_eur=24)

redditi <- redditi %>% filter(Regione != "Mancante/errata")

redditi %>% mutate(pro_capite = imponibile_eur / imponibile_n) -> redditi


shapes <- read_sf("Com01012022_g/Com01012022_g_WGS84.shp")

geo_redditi <- inner_join(shapes, redditi, 
                          by=c(PRO_COM_T="Codice Istat Comune"  ))
```

```{r}
geo_redditi %>% filter(Provincia == "TO") %>% 
ggplot(aes(geometry=geometry, fill=pro_capite))+
  scale_fill_distiller(palette=1,name="Reddito medio\npro-capite (€)")+
  geom_sf(color=NA)+
  geom_sf_label(aes(label=Comune),size=3, hjust="left", col="gold3",
               data = function(.d) .d %>% filter(pro_capite==max(pro_capite)))+
  geom_sf_label(aes(label=Comune),size=3, hjust="right", col="red",
               data = function(.d) .d %>% filter(pro_capite==min(pro_capite)))+
  theme_void()
```

-----

# Interazione con Shiny

```{r elementi di input}
tutte_province <- sort(unique(geo_redditi$Provincia))     # unique toglie i duplicati
tutte_regioni <- geo_redditi$Regione %>% unique() %>% sort()
selectInput("regione","Seleziona la regione",             # seleziona la regione
            choices=tutte_regioni)

selectInput("provincia","Seleziona la provincia",         # seleziona la provincia della regione
        #choices=c("TO","CN","AT","AL","VC","BI","VB","NO"),
        choices = tutte_province)
```

```{r elementi di output}
# hai qualcosa in output ma cosa? lo decide il server con funzione render_qualcosa => scende al server
plotOutput("mappa")
dataTableOutput("dati")
```



```{r server}
observeEvent( input$regione, {        # ho modificato da input la regione quindi esegui:  
  message("Regione: ",input$regione)  # stampa un messaggio in Render
  province_regione <- (redditi %>% filter(Regione==input$regione) %>% 
                       select(Provincia) %>% distinct() %>%
                       arrange(Provincia) )$Provincia
  updateSelectInput(inputId = "provincia",     # aggiorna dopo aver modificato input. Cosa devo aggiornare? "provincia". Cosa devo aggiornare di provincia? scelte:
                    choices =  province_regione)
})

output$mappa <- # plotOutput("mappa"
  renderPlot({  # voglio il plot della provincia messa da input
    geo_redditi %>% filter(Provincia == input$provincia) %>% # selectInput("provincia" perché così dici quale provincia vuoi plottata
      ggplot(aes(geometry=geometry, fill=pro_capite))+
      scale_fill_distiller(palette=1,name="Reddito medio\npro-capite (€)")+
      geom_sf(color=NA)+
      geom_sf_label(aes(label=Comune),size=3, hjust="left", col="gold3",
                    data = function(.d) .d %>% filter(pro_capite==max(pro_capite)))+
      geom_sf_label(aes(label=Comune),size=3, hjust="right", col="red",
                    data = function(.d) .d %>% filter(pro_capite==min(pro_capite)))+
      ggtitle(paste0("Provincia: ",input$provincia)) +
      theme_void()
    })


output$dati <- renderDataTable({  # dati per output
  redditi %>% 
  filter(Provincia==input$provincia) %>% 
    select(Comune,pro_capite,contribuenti)
})
```






